Feat/162727465/user signup validation
andela/merry-ah-backend pull request #14
Opened 2019-01-14 14:40 UTC by julietezekwe

#### What does this PR do?
Implements validation for user signup
#### Description of Task to be completed?
- Checks for valid email and user-type
- Checks for an empty field
- Checks if email exists
- Tests these functionalities
#### How should this be manually tested?
- On the signup route at `http:localhost:9000/api/v1/signup`
- Input invalid email or do not provide any required field and/or fill a required field with empty spaces; a descriptive error message will be displayed.
- Try signing up a user that already exists and get a descriptive error as well.

#### Any background context you want to provide?
 - None 

#### What are the relevant pivotal tracker stories?
[#162727465](https://www.pivotaltracker.com/story/show/162727465)

#### Screenshots (if appropriate)
- N/A

#### Questions:

2019-01-14 15:54 UTC, abejide001 approved these changes
LGTM

2019-01-14 19:56 UTC, wombolo approved these changes
Looks good

2019-01-15 09:07 UTC, andela-dbamidele requested changes
Looking good. I left some comments for you.

2019-01-15 09:07 UTC, andela-dbamidele commented on src/controllers/UsersController.js
> +        <a href='http://localhost:9000/api/v1/auth/user?token=${token}'>
Please don't hard-code the url.

2019-01-15 09:07 UTC, andela-dbamidele commented on src/controllers/UsersController.js
> +      await sendVerificationLink.sendEmail();
Will this throw an error if it fails?

2019-01-15 09:07 UTC, andela-dbamidele commented on src/middlewares/emailCheck.js
> +  const findEmail = await models.User.find({
Can you rename it to something better. findEmail seems a little bit off.

2019-01-15 09:07 UTC, andela-dbamidele commented on src/middlewares/userValidator.js
> +    const userTypes = ['user', 'artist'].includes(userType);
You should put the user types in a constant file instead of hardcoding them here. That will make it easier to change if there's any reason to add more user types.

2019-01-15 09:07 UTC, andela-dbamidele commented on src/middlewares/userValidator.js
> +    fieldValues.map((fieldValue) => {
Is this not a repetition of what you have in line 20 - 27?

2019-01-15 09:07 UTC, andela-dbamidele commented on src/routes/index.js
> +import authRouter from './usersRoute';
The name of the file and your export should be in sync.

2019-01-16 08:27 UTC, andela-dbamidele commented on src/db/migrations/20190114212257-create-comment.js
> +
Why do you have this in this PR?

2019-01-16 08:50 UTC, julietezekwe commented
Conflict resolved, unnecessary file removed as well. Thanks.

2019-01-16 09:37 UTC, andela-dbamidele approved these changes

2019-01-16 10:06 UTC, merged