#162727469 Create articles
andela/merry-ah-backend pull request #20
Opened 2019-01-16 19:34 UTC by wombolo

#### What does this PR do?
This enables authorised users create new articles that can be read by other users

#### Description of Task to be completed?

- Given two different users create articles of the same title, the app should generate unique slugs such that the articles don't create conflict.

- Users are able to CREATE articles and READ articles created by other Users.

- Users are able to ONLY UPDATE and DELETE articles that i have authored.

#### How should this be manually tested?
After migrations and installations of dependencies,
To Create an article, run POST > `http://localhost:9001/api/v1/articles` VALUES:
title:Cirrhosis of the Sky,
description:Cirrhosis of the Sky, The Syntax Podcasts isn't suitable for all ages,
categoryId:1,
media:[{"url":"https://farm3.staticflickr.com/2817/33968464326_a6f9cbc754_k","extension":"jpg"},   {"url":"https://images.pexels.com/photos/1047540/pexels-photo-1047540.jpeg?dl&fit=crop&crop=entropy&w=1280&h=853","extension":"jpeg"}]

To Edit an article, run PUT > `http://localhost:9001/api/v1/articles` VALUES:
title:Cirrhosis of the Sky,
description:Cirrhosis of the Sky, The Syntax Podcasts isn't suitable for all ages,
categoryId:1,
media:[{"url":"https://farm3.staticflickr.com/2817/33968464326_a6f9cbc754_k","extension":"jpg"},   {"url":"https://images.pexels.com/photos/1047540/pexels-photo-1047540.jpeg?dl&fit=crop&crop=entropy&w=1280&h=853","extension":"jpeg"}]

#### Any background context you want to provide?

- At least a Category is needed

#### What are the relevant pivotal tracker stories?
#### Screenshots (if appropriate)
#### Questions:

2019-01-16 19:38 UTC, abejide001 requested changes
Fix the houndci errors

2019-01-21 10:08 UTC, julietezekwe commented
Kindly check why the test is dropping. Check the catch blocks and the EmailNotificationAPI file.

2019-01-21 10:33 UTC, daniellamarr commented
Take all comments into consideration, then resolve conflicts

2019-01-21 10:34 UTC, daniellamarr reviewed
Resolve conflicts

2019-01-21 10:55 UTC, wombolo commented
> Kindly check why the test is dropping. Check the catch blocks and the EmailNotificationAPI file.

Coverage rose on the EmailNotificationAPI file, that catch blocks appear to be the issue

2019-01-21 11:48 UTC, daniellamarr commented on src/routes/artsRoute.js
> +const authRouter = express.Router();
Your file name and functionalities do not correlate, please attend to this

2019-01-21 11:49 UTC, daniellamarr commented on src/routes/artsRoute.js
> +export default authRouter;
Same thing here, you are using `authRouter` inside `artsRoute`

2019-01-21 12:03 UTC, julietezekwe commented
Please can you check why test is dropping

2019-01-21 12:04 UTC, julietezekwe reviewed
I dropped a comment on test coverage

2019-01-21 12:15 UTC, abejide001 commented on src/controllers/ArtsController.js
> +import { TokenAuthenticate, Response, Slugify } from '../helpers/index';
fix this errror

2019-01-21 12:17 UTC, wombolo commented on src/controllers/ArtsController.js
> +import { TokenAuthenticate, Response, Slugify } from '../helpers/index';
fixed

2019-01-21 12:26 UTC, abejide001 approved these changes

2019-01-21 15:58 UTC, Proception approved these changes

2019-01-22 09:26 UTC, andela-dbamidele approved these changes

2019-01-22 09:27 UTC, andela-dbamidele commented on test/controllers/artsControllerTest.js
> +        .put(`/api/v1/arts/ss-slug`)
Please use single quotes and not template strings

2019-01-22 09:32 UTC, wombolo commented on test/controllers/artsControllerTest.js
> +        .put(`/api/v1/arts/ss-slug`)
Thanks, I'm working on it.

2019-01-22 10:28 UTC, merged