#162727477 list users functionality
andela/merry-ah-backend pull request #22
Opened 2019-01-17 00:02 UTC by daniellamarr

#### What does this PR do?
- This PR list all available artists on the app
- This PR shows the profile of a particular artist
#### Description of Task to be completed?
- Authenticated users should be able to view a list of artists on the app
- Authenticated users should be able to view the profile of a particular artist on the app
#### How should this be manually tested?
- Run `npm i`
- Run `npm run db:migrate`
- Send a **GET** request to `/api/v1/users/artists`, you must be logged in and a token must be passed to the request before you can access the route. The route returns a list of all artists on the platform.
- Send a **GET** request to `/api/v1/users/artists/:artistId`, where `artistId` is the artist Id. Pass in access token before accessing the route. The route returns profile of a particular artist based on ID passed.
#### Any background context you want to provide?
- User must have signed up and logged in on the app before attempting to test this feature.
#### What are the relevant pivotal tracker stories?
[#162727477](https://www.pivotaltracker.com/story/show/162727477)
#### Screenshots (if appropriate)
<img width="1440" alt="screen shot 2019-01-17 at 12 46 17 am" src="https://user-images.githubusercontent.com/42177767/51286412-2cbf6980-19f3-11e9-95aa-07594902fe6e.png">
<img width="1440" alt="screen shot 2019-01-17 at 12 57 29 am" src="https://user-images.githubusercontent.com/42177767/51286413-2cbf6980-19f3-11e9-861c-ef0a09184592.png">

#### Questions:
N/A

2019-01-21 09:56 UTC, Proception reviewed
Looks good to me, however, resolve conflicts

2019-01-21 12:35 UTC, julietezekwe approved these changes
Looks good

2019-01-21 15:34 UTC, wombolo approved these changes
LGTM

2019-01-21 15:53 UTC, abejide001 approved these changes
LGTM

2019-01-22 11:45 UTC, andela-dbamidele requested changes

2019-01-22 11:45 UTC, andela-dbamidele commented on src/controllers/UsersController.js
> +      if (isNaN(artistId)) {
Can you move this to a middleware?

2019-01-22 11:48 UTC, daniellamarr commented on src/controllers/UsersController.js
> +      if (isNaN(artistId)) {
Alright

2019-01-22 11:58 UTC, daniellamarr commented on src/controllers/UsersController.js
> +      if (isNaN(artistId)) {
Done

2019-01-22 12:00 UTC, andela-dbamidele approved these changes
And also, please ensure that your commit messages describe the exact changes that you made.

2019-01-22 12:00 UTC, merged