Feature(Update profile):Users update profile feature
andela/merry-ah-backend pull request #24
Opened 2019-01-17 13:48 UTC by julietezekwe

#### What does this PR do?
This PR implements user profile update

#### Description of Task to be completed?
- Logged user can update their profile
- Input for the profile update is validated
- Test coverage for the added feature

#### How should this be manually tested?
-Login to the application and visit `http://localhost:9000/api/v1/users/profile`
- Input the required fields to update profile

#### Any background context you want to provide?
Required fields includes `bio`, `imgURL`, `userType`.

#### What are the relevant pivotal tracker stories?
[#163284045](https://www.pivotaltracker.com/story/show/163284045)

#### Screenshots (if appropriate)
None

#### Questions:
None

2019-01-21 10:08 UTC, abejide001 approved these changes
Looks good to me

2019-01-21 15:41 UTC, wombolo approved these changes
LGTM

2019-01-21 15:50 UTC, daniellamarr approved these changes
This is okay

2019-01-21 15:52 UTC, Proception reviewed
Looks good to me

2019-01-21 15:53 UTC, Proception approved these changes

2019-01-22 10:02 UTC, julietezekwe commented
This test drop is in no way relating to this feature, I made sure all passing tests are still passing and more.

2019-01-22 13:12 UTC, andela-dbamidele requested changes

2019-01-22 13:12 UTC, andela-dbamidele commented on src/controllers/UsersController.js
> +  static async updateProfile(req, res) {
The function name should compliment the url in the description. It's creating some confusion.

2019-01-22 13:12 UTC, andela-dbamidele commented on src/middlewares/ParamsChecker.js
> +    /* istanbul ignore next */if (userId) checkParam(userId);
Why this?

2019-01-22 13:12 UTC, andela-dbamidele commented on test/controllers/commentControllerTest.js
> +    it('it should comment add comment for a product that exists', (done) => {
Typo in the description

2019-01-22 13:40 UTC, julietezekwe commented on src/controllers/UsersController.js
> +  static async updateProfile(req, res) {
Fixed

2019-01-23 09:36 UTC, andela-dbamidele approved these changes

2019-01-23 09:36 UTC, merged